# Environment
x-stack-svc-env: &stack-svc-env
  APP_VERSION: ${STACK_VERSION:-0.0.1-alpha-0}
  APP_USER_ID: ${STACK_USER_ID:-1000}
  APP_GROUP_ID: ${STACK_GROUP_ID:-1000}
  STACK_NAME: ${STACK_NAME:-yellowteam}
  STACK_VERSION: ${STACK_VERSION:-0.0.1-alpha-0}
  STACK_ENV: ${STACK_ENV:-dev}  
  STACK_DOMAIN: ${STACK_DOMAIN:-yellowteam.dev}  
  TZ: ${STACK_TZ:-UTC}   
  # - USER_ID=1000
  # - GROUP_ID=1000
# Labels
x-stack-svc-labels: &stack-svc-labels
  app-version: ${STACK_VERSION:-0.0.1-alpha-0}
  node-id: '{{.Node.ID}}'
  node-hostname: '{{.Node.Hostname}}'
# Logger
x-stack-svc-logging: &stack-svc-logging
  driver: ${STACK_LOGGING_DRIVER:-json-file}
  options:    
    max-size: ${STACK_LOGGING_MAX_SIZE:-5m}
    max-file: ${STACK_LOGGING_MAX_FILE:-5} 

x-stack-svc: &stack-svc
  hostname: '{{.Node.Hostname}}.${STACK_NAME}.${STACK_ENV}.local'
  image: scratch
  # command: tail -f /dev/null
  environment:
    <<: *stack-svc-env
  extra_hosts:
    - "host.docker.internal:host-gateway"
    - "waf.${STACK_NAME}.${STACK_ENV}.local:${STACK_NETWORK_BRIDGE_PREFIX:-10.0.0}.2"
    - "dns.${STACK_NAME}.${STACK_ENV}.local:${STACK_NETWORK_BRIDGE_PREFIX:-10.0.0}.3"
  labels:
    <<: *stack-svc-labels
  logging:
    <<: *stack-svc-logging
  volumes:
    - stack-tmp:/tmp:rw
    - stack-logs:/var/log/yellow:rw
    - stack-data:/var/lib/yellow:rw
    - stack-tmpfs:/tmpfs:rw
    - /etc/localtime:/etc/localtime:ro
    # - /var/run/docker.sock:/var/run/docker.sock:ro
  networks:
    - stack
    # - stack-ipv6    
    # - stack-edge


services:
  stack-svc-base: &stack-svc-scratch
    <<: *stack-svc