name: yellowteam
services:
  authentik-postgresql:
    container_name: authentik-postgresql
    deploy:
      mode: replicated
      replicas: 1
      update_config:
        parallelism: 1
        delay: 10s
        order: stop-first
      rollback_config:
        parallelism: 1
        delay: 10s
        failure_action: rollback
        monitor: 1m0s
        order: stop-first
      resources:
        limits:
          cpus: 1
          memory: "524288000"
        reservations:
          cpus: 0.5
          memory: "1073741824"
      restart_policy:
        condition: on-failure
        delay: 30s
        max_attempts: 5
        window: 4m0s
    environment:
      APP_GROUP_ID: "1000"
      APP_USER_ID: "1000"
      APP_VERSION: 0.0.1-alpha-0
      POSTGRES_DB: authentik
      POSTGRES_PASSWORD: gctcMhCJHAsO4SlxVix+jPUHkvX90I8rVQNait93zkLEg4sn
      POSTGRES_USER: authentik
      STACK_DOMAIN: yellowteam.xyz
      STACK_ENV: dev
      STACK_NAME: yellowteam
      STACK_VERSION: 0.0.1-alpha-0
      TZ: UTC
    extra_hosts:
      - dns.yellowteam.dev.local=10.1.0.3
      - host.docker.internal=host-gateway
      - waf.yellowteam.dev.local=10.1.0.2
    hostname: '{{.Node.Hostname}}.yellowteam.dev.local'
    healthcheck:
      test:
        - CMD-SHELL
        - pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}
      timeout: 5s
      interval: 30s
      retries: 5
      start_period: 20s
    image: docker.io/library/postgres:17.4-alpine
    labels:
      app-version: 0.0.1-alpha-0
      node-hostname: '{{.Node.Hostname}}'
      node-id: '{{.Node.ID}}'
    logging:
      driver: json-file
      options:
        max-file: "5"
        max-size: 5m
    networks:
      stack: null
    restart: unless-stopped
    volumes:
      - type: volume
        source: stack-tmp
        target: /tmp
        volume: {}
      - type: volume
        source: stack-logs
        target: /var/log/yellow
        volume: {}
      - type: volume
        source: stack-data
        target: /var/lib/yellow
        volume: {}
      - type: volume
        source: stack-tmpfs
        target: /tmpfs
        volume: {}
      - type: bind
        source: /etc/localtime
        target: /etc/localtime
        read_only: true
        bind:
          create_host_path: true
      - type: volume
        source: authentik-database
        target: /var/lib/postgresql/data
        volume: {}
  authentik-proxy:
    container_name: authentik-proxy
    depends_on:
      authentik-server:
        condition: service_healthy
        required: true
    deploy:
      mode: replicated
      replicas: 1
      update_config:
        parallelism: 1
        delay: 10s
        order: stop-first
      rollback_config:
        parallelism: 1
        delay: 10s
        failure_action: rollback
        monitor: 1m0s
        order: stop-first
      resources:
        limits:
          cpus: 1
          memory: "524288000"
        reservations:
          cpus: 0.5
          memory: "1073741824"
      restart_policy:
        condition: on-failure
        delay: 30s
        max_attempts: 5
        window: 4m0s
    environment:
      APP_GROUP_ID: "1000"
      APP_USER_ID: "1000"
      APP_VERSION: 0.0.1-alpha-0
      AUTHENTIK_DEBUG: "true"
      AUTHENTIK_HOST: http://authentik-server:9000
      AUTHENTIK_HOST_BROWSER: https://authentik.yellowteam.xyz
      AUTHENTIK_INSECURE: "false"
      AUTHENTIK_PORT: "9000"
      AUTHENTIK_TOKEN: 0TipH+mrxqOoVzCBRwmMBX45ItzdPEaknXdENjWfFOgkxJG1zSonY+qK2jf0GaC3sU/ZHB6PWqigPOT+
      STACK_DOMAIN: yellowteam.xyz
      STACK_ENV: dev
      STACK_NAME: yellowteam
      STACK_VERSION: 0.0.1-alpha-0
      TZ: UTC
    extra_hosts:
      - dns.yellowteam.dev.local=10.1.0.3
      - host.docker.internal=host-gateway
      - waf.yellowteam.dev.local=10.1.0.2
    hostname: '{{.Node.Hostname}}.yellowteam.dev.local'
    image: ghcr.io/goauthentik/proxy:2025.2.1
    labels:
      app-version: 0.0.1-alpha-0
      node-hostname: '{{.Node.Hostname}}'
      node-id: '{{.Node.ID}}'
      traefik.enable: "true"
      traefik.http.routers.authentik-output.entrypoints: websecure
      traefik.http.routers.authentik-output.middlewares: authentik@file
      traefik.http.routers.authentik-output.rule: HostRegexp(`{subdomain:[a-z0-9-]+}.yellowteam.xyz`) && PathPrefix(`/outpost.goauthentik.io/auth/traefik`)
      traefik.http.routers.authentik-output.tls: "true"
      traefik.http.routers.authentik-output.tls.certresolver: staging
      traefik.http.services.authentik-output.loadbalancer.server.port: "9000"
    logging:
      driver: json-file
      options:
        max-file: "5"
        max-size: 5m
    networks:
      stack: null
      stack-edge: null
    ports:
      - mode: ingress
        target: 9000
        published: "9000"
        protocol: tcp
      - mode: ingress
        target: 9443
        published: "9443"
        protocol: tcp
    restart: always
    volumes:
      - type: volume
        source: stack-tmp
        target: /tmp
        volume: {}
      - type: volume
        source: stack-logs
        target: /var/log/yellow
        volume: {}
      - type: volume
        source: stack-data
        target: /var/lib/yellow
        volume: {}
      - type: volume
        source: stack-tmpfs
        target: /tmpfs
        volume: {}
      - type: bind
        source: /etc/localtime
        target: /etc/localtime
        read_only: true
        bind:
          create_host_path: true
  authentik-redis:
    command:
      - --save
      - "60"
      - "1"
      - --loglevel
      - warning
    container_name: authentik-redis
    deploy:
      mode: replicated
      replicas: 1
      update_config:
        parallelism: 1
        delay: 10s
        order: stop-first
      rollback_config:
        parallelism: 1
        delay: 10s
        failure_action: rollback
        monitor: 1m0s
        order: stop-first
      resources:
        limits:
          cpus: 1
          memory: "524288000"
        reservations:
          cpus: 0.5
          memory: "1073741824"
      restart_policy:
        condition: on-failure
        delay: 30s
        max_attempts: 5
        window: 4m0s
    environment:
      APP_GROUP_ID: "1000"
      APP_USER_ID: "1000"
      APP_VERSION: 0.0.1-alpha-0
      STACK_DOMAIN: yellowteam.xyz
      STACK_ENV: dev
      STACK_NAME: yellowteam
      STACK_VERSION: 0.0.1-alpha-0
      TZ: UTC
    extra_hosts:
      - dns.yellowteam.dev.local=10.1.0.3
      - host.docker.internal=host-gateway
      - waf.yellowteam.dev.local=10.1.0.2
    hostname: '{{.Node.Hostname}}.yellowteam.dev.local'
    healthcheck:
      test:
        - CMD-SHELL
        - redis-cli ping | grep PONG
      timeout: 3s
      interval: 30s
      retries: 5
      start_period: 20s
    image: docker.io/library/redis:7.4.2-alpine
    labels:
      app-version: 0.0.1-alpha-0
      node-hostname: '{{.Node.Hostname}}'
      node-id: '{{.Node.ID}}'
    logging:
      driver: json-file
      options:
        max-file: "5"
        max-size: 5m
    networks:
      stack: null
    restart: unless-stopped
    volumes:
      - type: volume
        source: stack-tmp
        target: /tmp
        volume: {}
      - type: volume
        source: stack-logs
        target: /var/log/yellow
        volume: {}
      - type: volume
        source: stack-data
        target: /var/lib/yellow
        volume: {}
      - type: volume
        source: stack-tmpfs
        target: /tmpfs
        volume: {}
      - type: bind
        source: /etc/localtime
        target: /etc/localtime
        read_only: true
        bind:
          create_host_path: true
      - type: volume
        source: authentik-redis
        target: /data
        volume: {}
  authentik-server:
    command:
      - server
    container_name: authentik-server
    depends_on:
      authentik-postgresql:
        condition: service_healthy
        required: true
      authentik-redis:
        condition: service_healthy
        required: true
    deploy:
      mode: replicated
      replicas: 1
      update_config:
        parallelism: 1
        delay: 10s
        order: stop-first
      rollback_config:
        parallelism: 1
        delay: 10s
        failure_action: rollback
        monitor: 1m0s
        order: stop-first
      resources:
        limits:
          cpus: 1
          memory: "524288000"
        reservations:
          cpus: 0.5
          memory: "1073741824"
      restart_policy:
        condition: on-failure
        delay: 30s
        max_attempts: 5
        window: 4m0s
    environment:
      APP_GROUP_ID: "1000"
      APP_USER_ID: "1000"
      APP_VERSION: 0.0.1-alpha-0
      AUTHENTIK_COOKIE_DOMAIN: yellowteam.xyz
      AUTHENTIK_EMAIL__FROM: auth@authentik.com
      AUTHENTIK_EMAIL__HOST: smtp.gmail.com
      AUTHENTIK_EMAIL__PASSWORD: "1"
      AUTHENTIK_EMAIL__PORT: "587"
      AUTHENTIK_EMAIL__TIMEOUT: "5"
      AUTHENTIK_EMAIL__USE_SSL: "true"
      AUTHENTIK_EMAIL__USE_TLS: "true"
      AUTHENTIK_EMAIL__USERNAME: "1"
      AUTHENTIK_ERROR_REPORTING__ENABLED: "false"
      AUTHENTIK_HOST: http://authentik-server:9000
      AUTHENTIK_HOST_BROWSER: https://authentik.yellowteam.xyz
      AUTHENTIK_POSTGRESQL__HOST: authentik-postgresql
      AUTHENTIK_POSTGRESQL__NAME: authentik
      AUTHENTIK_POSTGRESQL__PASSWORD: gctcMhCJHAsO4SlxVix+jPUHkvX90I8rVQNait93zkLEg4sn
      AUTHENTIK_POSTGRESQL__USER: authentik
      AUTHENTIK_REDIS__HOST: authentik-redis
      AUTHENTIK_SECRET_KEY: 0TipH+mrxqOoVzCBRwmMBX45ItzdPEaknXdENjWfFOgkxJG1zSonY+qK2jf0GaC3sU/ZHB6PWqigPOT+
      STACK_DOMAIN: yellowteam.xyz
      STACK_ENV: dev
      STACK_NAME: yellowteam
      STACK_VERSION: 0.0.1-alpha-0
      TZ: UTC
    extra_hosts:
      - dns.yellowteam.dev.local=10.1.0.3
      - host.docker.internal=host-gateway
      - waf.yellowteam.dev.local=10.1.0.2
    hostname: '{{.Node.Hostname}}.yellowteam.dev.local'
    image: ghcr.io/goauthentik/server:2025.2.1
    labels:
      app-version: 0.0.1-alpha-0
      node-hostname: '{{.Node.Hostname}}'
      node-id: '{{.Node.ID}}'
      traefik.enable: "true"
      traefik.http.routers.authentik.entrypoints: websecure
      traefik.http.routers.authentik.rule: Host(`authentik.yellowteam.xyz`)
      traefik.http.routers.authentik.tls: "true"
      traefik.http.routers.authentik.tls.certresolver: staging
      traefik.http.services.authentik.loadbalancer.healthcheck.path: /-/health/live/
      traefik.http.services.authentik.loadbalancer.server.port: "9000"
    logging:
      driver: json-file
      options:
        max-file: "5"
        max-size: 5m
    networks:
      stack: null
    restart: unless-stopped
    volumes:
      - type: volume
        source: stack-tmp
        target: /tmp
        volume: {}
      - type: volume
        source: stack-logs
        target: /var/log/yellow
        volume: {}
      - type: volume
        source: stack-data
        target: /var/lib/yellow
        volume: {}
      - type: volume
        source: stack-tmpfs
        target: /tmpfs
        volume: {}
      - type: bind
        source: /etc/localtime
        target: /etc/localtime
        read_only: true
        bind:
          create_host_path: true
      - type: bind
        source: /develop/.vcs/github/ywteam/workspace/src/bart/templates/docker/apps/authentik/data/media
        target: /media
        bind:
          create_host_path: true
      - type: bind
        source: /develop/.vcs/github/ywteam/workspace/src/bart/templates/docker/apps/authentik/data/templates
        target: /templates
        bind:
          create_host_path: true
  authentik-worker:
    command:
      - worker
    depends_on:
      authentik-postgresql:
        condition: service_healthy
        required: true
      authentik-redis:
        condition: service_healthy
        required: true
    deploy:
      mode: replicated
      replicas: 2
      update_config:
        parallelism: 1
        delay: 10s
        order: stop-first
      rollback_config:
        parallelism: 1
        delay: 10s
        failure_action: rollback
        monitor: 1m0s
        order: stop-first
      resources:
        limits:
          cpus: 1
          memory: "524288000"
        reservations:
          cpus: 0.5
          memory: "1073741824"
      restart_policy:
        condition: on-failure
        delay: 30s
        max_attempts: 5
        window: 4m0s
    environment:
      APP_GROUP_ID: "1000"
      APP_USER_ID: "1000"
      APP_VERSION: 0.0.1-alpha-0
      AUTHENTIK_COOKIE_DOMAIN: yellowteam.xyz
      AUTHENTIK_EMAIL__FROM: auth@authentik.com
      AUTHENTIK_EMAIL__HOST: smtp.gmail.com
      AUTHENTIK_EMAIL__PASSWORD: "1"
      AUTHENTIK_EMAIL__PORT: "587"
      AUTHENTIK_EMAIL__TIMEOUT: "5"
      AUTHENTIK_EMAIL__USE_SSL: "true"
      AUTHENTIK_EMAIL__USE_TLS: "true"
      AUTHENTIK_EMAIL__USERNAME: "1"
      AUTHENTIK_ERROR_REPORTING__ENABLED: "false"
      AUTHENTIK_HOST: http://authentik-server:9000
      AUTHENTIK_HOST_BROWSER: https://authentik.yellowteam.xyz
      AUTHENTIK_POSTGRESQL__HOST: authentik-postgresql
      AUTHENTIK_POSTGRESQL__NAME: authentik
      AUTHENTIK_POSTGRESQL__PASSWORD: gctcMhCJHAsO4SlxVix+jPUHkvX90I8rVQNait93zkLEg4sn
      AUTHENTIK_POSTGRESQL__USER: authentik
      AUTHENTIK_REDIS__HOST: authentik-redis
      AUTHENTIK_SECRET_KEY: 0TipH+mrxqOoVzCBRwmMBX45ItzdPEaknXdENjWfFOgkxJG1zSonY+qK2jf0GaC3sU/ZHB6PWqigPOT+
      STACK_DOMAIN: yellowteam.xyz
      STACK_ENV: dev
      STACK_NAME: yellowteam
      STACK_VERSION: 0.0.1-alpha-0
      TZ: UTC
    extra_hosts:
      - dns.yellowteam.dev.local=10.1.0.3
      - host.docker.internal=host-gateway
      - waf.yellowteam.dev.local=10.1.0.2
    hostname: '{{.Node.Hostname}}.yellowteam.dev.local'
    image: ghcr.io/goauthentik/server:2025.2.1
    labels:
      app-version: 0.0.1-alpha-0
      node-hostname: '{{.Node.Hostname}}'
      node-id: '{{.Node.ID}}'
    logging:
      driver: json-file
      options:
        max-file: "5"
        max-size: 5m
    networks:
      stack: null
    restart: unless-stopped
    user: root
    volumes:
      - type: volume
        source: stack-tmp
        target: /tmp
        volume: {}
      - type: volume
        source: stack-logs
        target: /var/log/yellow
        volume: {}
      - type: volume
        source: stack-data
        target: /var/lib/yellow
        volume: {}
      - type: volume
        source: stack-tmpfs
        target: /tmpfs
        volume: {}
      - type: bind
        source: /etc/localtime
        target: /etc/localtime
        read_only: true
        bind:
          create_host_path: true
      - type: volume
        source: authentik-certs
        target: /certs
        volume: {}
      - type: bind
        source: /develop/.vcs/github/ywteam/workspace/src/bart/templates/docker/apps/authentik/data/media
        target: /media
        bind:
          create_host_path: true
      - type: bind
        source: /develop/.vcs/github/ywteam/workspace/src/bart/templates/docker/apps/authentik/data/templates
        target: /templates
        bind:
          create_host_path: true
  error-pages:
    container_name: error-pages
    environment:
      APP_GROUP_ID: "1000"
      APP_USER_ID: "1000"
      APP_VERSION: 0.0.1-alpha-0
      STACK_DOMAIN: yellowteam.xyz
      STACK_ENV: dev
      STACK_NAME: yellowteam
      STACK_VERSION: 0.0.1-alpha-0
      TEMPLATE_NAME: lost-in-space
      TZ: UTC
    extra_hosts:
      - dns.yellowteam.dev.local=10.1.0.3
      - host.docker.internal=host-gateway
      - waf.yellowteam.dev.local=10.1.0.2
    hostname: '{{.Node.Hostname}}.yellowteam.dev.local'
    image: ghcr.io/tarampampam/error-pages:3.3.2
    labels:
      app-version: 0.0.1-alpha-0
      node-hostname: '{{.Node.Hostname}}'
      node-id: '{{.Node.ID}}'
      traefik.enable: "true"
      traefik.http.middlewares.error-pages-middleware.errors.query: /{{status}}.html
      traefik.http.middlewares.error-pages-middleware.errors.service: error-pages
      traefik.http.middlewares.error-pages-middleware.errors.status: 400-599
      traefik.http.routers.error-pages-router.middlewares: error-pages-middleware
      traefik.http.routers.error-pages-router.priority: "10"
      traefik.http.routers.error-pages.entrypoints: web
      traefik.http.routers.error-pages.rule: HostRegexp(`.+`)
      traefik.http.services.error-pages.loadbalancer.server.port: "8080"
    logging:
      driver: json-file
      options:
        max-file: "5"
        max-size: 5m
    networks:
      stack: null
    volumes:
      - type: volume
        source: stack-tmp
        target: /tmp
        volume: {}
      - type: volume
        source: stack-logs
        target: /var/log/yellow
        volume: {}
      - type: volume
        source: stack-data
        target: /var/lib/yellow
        volume: {}
      - type: volume
        source: stack-tmpfs
        target: /tmpfs
        volume: {}
      - type: bind
        source: /etc/localtime
        target: /etc/localtime
        read_only: true
        bind:
          create_host_path: true
  traefik:
    container_name: traefik
    deploy:
      mode: global
      update_config:
        parallelism: 1
        delay: 10s
        order: stop-first
      rollback_config:
        parallelism: 1
        delay: 10s
        failure_action: rollback
        monitor: 1m0s
        order: stop-first
      resources:
        limits:
          cpus: 2
          memory: "1073741824"
        reservations:
          cpus: 0.75
          memory: "2147483648"
      restart_policy:
        condition: on-failure
        delay: 30s
        max_attempts: 5
        window: 4m0s
    environment:
      ACME_EMAIL: raphaelcarlosr@gmail.com
      APP_GROUP_ID: "1000"
      APP_USER_ID: "1000"
      APP_VERSION: 0.0.1-alpha-0
      CF_API_EMAIL: raphaelcarlosr@gmail.com
      CF_API_KEY: DdvvamtS1vryf5MGQBZtSlJabufi6h0ODipYBYHK
      STACK_DOMAIN: yellowteam.xyz
      STACK_ENV: dev
      STACK_NAME: yellowteam
      STACK_VERSION: 0.0.1-alpha-0
      TRAEFIK_AUTH_ENABLED: "true"
      TRAEFIK_AUTH_PASS_HASH: '''$$apr1$$yzXCOaAe$$nn6/HUwjA/QwHLTaF6DYT1'''
      TRAEFIK_AUTH_USER: admin
      TRAEFIK_DASHBOARD_CREDENTIALS: ""
      TRAEFIK_LOG_LEVEL: DEBUG
      TZ: UTC
    extra_hosts:
      - dns.yellowteam.dev.local=10.1.0.3
      - host.docker.internal=host-gateway
      - waf.yellowteam.dev.local=10.1.0.2
    hostname: '{{.Node.Hostname}}.yellowteam.dev.local'
    image: traefik:v3.3.4
    labels:
      app-version: 0.0.1-alpha-0
      node-hostname: '{{.Node.Hostname}}'
      node-id: '{{.Node.ID}}'
      traefik.enable: "true"
      traefik.http.routers.ping.rule: Host(`traefik.yellowteam.xyz`) && Path(`/ping`)
      traefik.http.routers.ping.service: ping@internal
      traefik.http.routers.ping.tls: "true"
      traefik.http.routers.ping.tls.certresolver: staging
      traefik.http.routers.traefik.middlewares: basic-auth@file
      traefik.http.routers.traefik.rule: Host(`traefik.yellowteam.xyz`) && (PathPrefix(`/api`) || PathPrefix(`/dashboard`))
      traefik.http.routers.traefik.service: api@internal
      traefik.http.routers.traefik.tls: "true"
      traefik.http.routers.traefik.tls.certresolver: staging
      traefik.http.services.noop-service.loadbalancer.server.port: "80"
      traefik.http.services.traefik.loadbalancer.server.port: "8080"
    logging:
      driver: json-file
      options:
        max-file: "5"
        max-size: 5m
    networks:
      stack: null
      stack-edge: null
    ports:
      - mode: ingress
        target: 80
        published: "80"
        protocol: tcp
      - mode: ingress
        target: 8080
        published: "8080"
        protocol: tcp
      - mode: ingress
        target: 443
        published: "443"
        protocol: tcp
    volumes:
      - type: volume
        source: stack-tmp
        target: /tmp
        volume: {}
      - type: volume
        source: stack-logs
        target: /var/log/yellow
        volume: {}
      - type: volume
        source: stack-data
        target: /var/lib/yellow
        volume: {}
      - type: volume
        source: stack-tmpfs
        target: /tmpfs
        volume: {}
      - type: bind
        source: /etc/localtime
        target: /etc/localtime
        read_only: true
        bind:
          create_host_path: true
      - type: bind
        source: /var/run/docker.sock
        target: /var/run/docker.sock
        read_only: true
        bind:
          create_host_path: true
      - type: bind
        source: /develop/.vcs/github/ywteam/workspace/src/bart/templates/docker/apps/traefik/config
        target: /etc/traefik/config
        bind:
          create_host_path: true
      - type: bind
        source: /develop/.vcs/github/ywteam/workspace/src/bart/templates/docker/apps/traefik/traefik.yaml
        target: /etc/traefik/traefik.yaml
        bind:
          create_host_path: true
      - type: volume
        source: traefik-acme
        target: /letsencrypt
        volume: {}
  whoami:
    container_name: whoami
    environment:
      APP_GROUP_ID: "1000"
      APP_USER_ID: "1000"
      APP_VERSION: 0.0.1-alpha-0
      STACK_DOMAIN: yellowteam.xyz
      STACK_ENV: dev
      STACK_NAME: yellowteam
      STACK_VERSION: 0.0.1-alpha-0
      TZ: UTC
    extra_hosts:
      - dns.yellowteam.dev.local=10.1.0.3
      - host.docker.internal=host-gateway
      - waf.yellowteam.dev.local=10.1.0.2
    hostname: '{{.Node.Hostname}}.yellowteam.dev.local'
    image: containous/whoami
    labels:
      app-version: 0.0.1-alpha-0
      node-hostname: '{{.Node.Hostname}}'
      node-id: '{{.Node.ID}}'
      traefik.enable: "true"
      traefik.http.routers.whoami.entrypoints: websecure
      traefik.http.routers.whoami.middlewares: authentik@file
      traefik.http.routers.whoami.rule: Host(`whoami.yellowteam.xyz`) && PathPrefix(`/me`)
      traefik.http.routers.whoami.tls: "true"
      traefik.http.routers.whoami.tls.certresolver: staging
      traefik.http.services.whoami.loadbalancer.server.port: "80"
    logging:
      driver: json-file
      options:
        max-file: "5"
        max-size: 5m
    networks:
      stack: null
    volumes:
      - type: volume
        source: stack-tmp
        target: /tmp
        volume: {}
      - type: volume
        source: stack-logs
        target: /var/log/yellow
        volume: {}
      - type: volume
        source: stack-data
        target: /var/lib/yellow
        volume: {}
      - type: volume
        source: stack-tmpfs
        target: /tmpfs
        volume: {}
      - type: bind
        source: /etc/localtime
        target: /etc/localtime
        read_only: true
        bind:
          create_host_path: true
networks:
  stack:
    name: yellowteam-dev-network
    driver: overlay
    driver_opts:
      com.docker.network.bridge.enable_icc: "true"
      com.docker.network.bridge.enable_ip_masquerade: "false"
      com.docker.network.driver.mtu: "1500"
    ipam:
      driver: default
      config:
        - subnet: 10.1.0.0/24
          gateway: 10.1.0.1
          ip_range: 10.1.0.0/24
          aux_addresses:
            pihole: 10.1.0.3
            safeline: 10.1.0.2
    attachable: true
    enable_ipv4: true
    enable_ipv6: false
  stack-edge:
    name: yellowteam-dev-edge
    driver: overlay
    attachable: true
    enable_ipv4: true
    enable_ipv6: false
volumes:
  authentik-certs:
    name: yellowteam-dev-authentik-certs
    driver: local
  authentik-database:
    name: yellowteam-dev-authentik-postgresql
    driver: local
  authentik-redis:
    name: yellowteam-dev-authentik-redis
    driver: local
    driver_opts:
      device: tmpfs
      type: tmpfs
  stack-data:
    name: yellowteam-dev-data
    driver: local
    driver_opts:
      device: tmpfs
      type: tmpfs
  stack-logs:
    name: yellowteam-dev-logs
    driver: local
    driver_opts:
      device: /var/log/yellowteam
      o: bind
      type: none
  stack-tmp:
    name: yellowteam-dev-tmp
    driver: local
    driver_opts:
      device: /tmp/yellowteam
      o: bind
      type: none
  stack-tmpfs:
    name: yellowteam-dev-tmpfs
    driver: local
    driver_opts:
      device: tmpfs
      type: tmpfs
  traefik-acme:
    name: yellowteam-dev-traefik-acme
    driver: local
