x-traefik-svc: &traefik-svc
  extends:
    file: ../../compose.deployments.yaml
    service: stack-svc-global-large
  networks:
    - stack-edge

services:
  traefik:
    <<: *traefik-svc
    image: traefik:${SVC_TRAEFIK_VERSION:-v3.3.4} # https://hub.docker.com/_/traefik/tags
    container_name: traefik
    environment:
      - ACME_EMAIL=${SVC_TRAEFIK_ACME_EMAIL}
      # - ACME_STORAGE=/letsencrypt/acme.json
      - TRAEFIK_DASHBOARD_CREDENTIALS=${SVC_TRAEFIK_DASHBOARD_CREDENTIALS}
      - CF_API_KEY=${CF_API_KEY}
      - CF_API_EMAIL=${CF_API_EMAIL}
      - TRAEFIK_LOG_LEVEL=${SVC_TRAEFIK_LOG_LEVEL:-INFO}  # Added logging level
      - TRAEFIK_AUTH_USER=${SVC_TRAEFIK_AUTH_USER:-admin}
      - TRAEFIK_AUTH_PASS_HASH=${SVC_TRAEFIK_AUTH_PASSWORD_HASH:-'$apr1$yzXCOaAe$nn6/HUwjA/QwHLTaF6DYT1'}
      - TRAEFIK_AUTH_ENABLED=true  # Added environment variable to enable basic auth
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /etc/localtime:/etc/localtime:ro
      - ${STACK_CURRENT_DIR}/apps/traefik/config:/etc/traefik/config #:rw
      - ${STACK_CURRENT_DIR}/apps/traefik/traefik.yaml:/etc/traefik/traefik.yaml
      - traefik-acme:/letsencrypt:rw
    ports:
      - "80:80" 
      - 8080:8080  #"127.0.0.1:8080:8080"
      - 443:443
    #   - "5001:443" # Needed for SNI challenge
    #   - "5002:80" # Needed for HTTP challenge
    labels:
      - "traefik.enable=true"
      # Dashboard
      - "traefik.http.routers.traefik.rule=Host(`traefik.${STACK_DOMAIN}`) && (PathPrefix(`/api`) || PathPrefix(`/dashboard`))" 
      - "traefik.http.routers.traefik.service=api@internal"
      - "traefik.http.routers.traefik.tls=true"
      - "traefik.http.routers.traefik.tls.certresolver=staging"
      - "traefik.http.services.traefik.loadbalancer.server.port=8080"
      - "traefik.http.routers.traefik.middlewares=basic-auth@file"  # error-pages-middleware
      # Ping is open to the world to let third party monitor traefik availability / healthcheck) (without basicauth)
      - "traefik.http.routers.ping.rule=Host(`traefik.${STACK_DOMAIN}`) && Path(`/ping`)"
      - "traefik.http.routers.ping.service=ping@internal"
      - "traefik.http.routers.ping.tls.certresolver=staging"
      - "traefik.http.routers.ping.tls=true"      
      # Global redirect to HTTPS
      # - "traefik.http.routers.http-catchall.rule=hostregexp(`{host:.+}`)"
      # - "traefik.http.routers.http-catchall.entrypoints=web"
      # - "traefik.http.routers.http-catchall.middlewares=redirect-to-https"
      # Middleware for HTTPS redirect
      # - "traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https"
      # Global HTTPS catchall
      # - "traefik.http.routers.catchall-router.rule=HostRegexp(`{host:.+}`)"
      # - "traefik.http.routers.catchall-router.entrypoints=websecure"
      # - "traefik.http.routers.catchall-router.middlewares=authentik@file"
      # - "traefik.http.routers.catchall-router.tls.certresolver=staging"
      # Dummy service for the catchall router
      - "traefik.http.services.noop-service.loadbalancer.server.port=80"
      # Safeline
      # - "traefik.http.middlewares.waf.plugin.safeline.addr=safeline-detector:8000"
      # Modsecurity
      # - "traefik.http.middlewares.modsecurity.plugin.modsecurity.modSecurityUrl=http://waf:80"
      # - "traefik.http.middlewares.modsecurity.plugin.modsecurity.maxBodySize=10485760"
  error-pages:
    extends:
      file: ../../compose.deployments.yaml
      service: stack-svc-base
    container_name: error-pages
    image: ghcr.io/tarampampam/error-pages:3.3.2
    environment:
      - TEMPLATE_NAME=lost-in-space
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.error-pages.rule=HostRegexp(`.+`)"
      - "traefik.http.routers.error-pages-router.priority=10"
      - "traefik.http.routers.error-pages.entrypoints=web"
      - "traefik.http.routers.error-pages-router.middlewares=error-pages-middleware"
      - "traefik.http.middlewares.error-pages-middleware.errors.status=400-599"
      - "traefik.http.middlewares.error-pages-middleware.errors.service=error-pages"
      - "traefik.http.middlewares.error-pages-middleware.errors.query=/{{status}}.html"
      - "traefik.http.services.error-pages.loadbalancer.server.port=8080"
  whoami:
    extends:
      file: ../../compose.deployments.yaml
      service: stack-svc-base
    image: "containous/whoami"
    container_name: whoami
    labels:
        - "traefik.enable=true"
        - "traefik.http.routers.whoami.rule=Host(`whoami.${STACK_DOMAIN}`) && PathPrefix(`/me`)"
        - "traefik.http.routers.whoami.entrypoints=websecure"
        - "traefik.http.routers.whoami.tls=true"
        - "traefik.http.routers.whoami.tls.certresolver=staging"
        - "traefik.http.services.whoami.loadbalancer.server.port=80"
        - "traefik.http.routers.whoami.middlewares=authentik@file"
        # - "traefik.http.routers.whoami-public.rule=Host(`whoami.${STACK_DOMAIN}`) && PathPrefix(`/`)"
        # - "traefik.http.routers.whoami-public.entrypoints=websecure"
        # - "traefik.http.routers.whoami-public.tls=true"
        # - "traefik.http.routers.whoami-public.tls.certresolver=staging"
        # - "traefik.http.services.whoami-public.loadbalancer.server.port=80"
        # - "traefik.http.middlewares.waf.plugin.safeline.addr=safeline-detector:8000"
  

volumes:
  traefik-acme:
    name: ${STACK_PREFIX}-traefik-acme
    driver: local 